# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import poed_ipc_pb2 as poed__ipc__pb2


class PoeIpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandlePoecli = channel.unary_unary(
            "/PoedIpc.PoeIpc/HandlePoecli",
            request_serializer=poed__ipc__pb2.PoecliRequest.SerializeToString,
            response_deserializer=poed__ipc__pb2.PoecliReply.FromString,
        )


class PoeIpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HandlePoecli(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PoeIpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "HandlePoecli": grpc.unary_unary_rpc_method_handler(
            servicer.HandlePoecli,
            request_deserializer=poed__ipc__pb2.PoecliRequest.FromString,
            response_serializer=poed__ipc__pb2.PoecliReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("PoedIpc.PoeIpc", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class PoeIpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HandlePoecli(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/PoedIpc.PoeIpc/HandlePoecli",
            poed__ipc__pb2.PoecliRequest.SerializeToString,
            poed__ipc__pb2.PoecliReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
